[package]
name = "jvmti-sample"
version = "0.5.0"
authors = [ "Robert Lu <robberphex@gmail.com>" ]
description = "Java native agent example"
keywords = [ "java", "jvm", "jvmti", "debugger" ]

[lib]
crate_type = [ "cdylib", "rlib" ]

[dependencies]
jvmti = {path = "../jvmti", version = "0.5.0"}
